version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gsandoo/coalarm:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    restart: always
