spring:
  datasource:
    url: jdbc:postgresql://15.164.221.182:5432/coalarm
    username: coalarm
    password: qwer2345678!
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  paths-to-match: /**
