apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: gsandoo/coalarm:__IMAGE_TAG__
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: db-secret
            - secretRef:
                name: aws-secret
            - secretRef:
                name: jwt-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prd
      restartPolicy: Always
