env:
  IMAGE_NAME: gsandoo/coalarm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout source code
        uses: actions/checkout@v3

      - name: 🔐 Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🐳 Build Docker image with Git SHA tag
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: 📤 Push image to Docker Hub with SHA tag
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: ☸️ Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: 🚀 Deploy to Kubernetes (with SHA image)
        run: |
          sed "s|__IMAGE_TAG__|${{ github.sha }}|g" k8s/deployment.yaml | kubectl apply -f -
